services:
  reactive-video-mongo:
    image: mongo:7
    container_name: reactive-video-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db:rw
    networks:
      - compose-reactive-video-network
    restart: unless-stopped
  reactive-video-minio:
    image: minio/minio
    container_name: reactive-video-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data:rw
    environment:
      MINIO_ACCESS_KEY: S3_ACCESS_KEY
      MINIO_SECRET_KEY: S3_SECRET_KEY
    command: server /data --console-address ":9001"
    networks:
      - compose-reactive-video-network
  reactive-video-backend:
    depends_on:
     - reactive-video-mongo
     - reactive-video-minio
    build:
      context: ../
      dockerfile: devops/backend.Dockerfile
    image: reactive-video:1.0
    container_name: reactive-video-backend
    ports:
      - '8081:8081'
    environment:
      - MONGODB_URI=mongodb://reactive-video-mongo:27017/files
      - S3_HOST=http://reactive-video-minio:9000
      - S3_ACCESS_KEY=S3_ACCESS_KEY
      - S3_SECRET_KEY=S3_SECRET_KEY
      - VK_VISION_OAUTH_CLIENT_ID=VK_VISION_OAUTH_CLIENT_ID
      - VK_VISION_OAUTH_REFRESH_TOKEN=VK_VISION_OAUTH_REFRESH_TOKEN
      - VK_VOICE_OAUTH_CLIENT_ID=VK_VOICE_OAUTH_CLIENT_ID
      - VK_VOICE_OAUTH_REFRESH_TOKEN=VK_VOICE_OAUTH_REFRESH_TOKEN
    env_file:
      - backend.env
    networks:
      - compose-reactive-video-network
  reactive-video-frontend:
    depends_on:
      - reactive-video-backend
    build:
      context: ../
      dockerfile: devops/frontend.Dockerfile
    image: reactive-video-frontend:1.0
    container_name: reactive-video-frontend
    environment:
      - BACKEND_HOST=reactive-video-backend:8081
    ports:
      - '8080:80'
    networks:
      - compose-reactive-video-network

networks:
  compose-reactive-video-network:
    driver: bridge
    name: compose-reactive-video-network
volumes:
  mongo-data: {}
