services:
  reactive-video-mongo:
    image: mongo:7
    container_name: reactive-video-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db:rw
    networks:
      - network
    restart: unless-stopped
  reactive-video-minio:
    image: quay.io/minio/minio
    container_name: reactive-video-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data:rw
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY
      MINIO_SECRET_KEY: SECRET_KEY
    command: server /data --console-address ":9001"
    networks:
      - network
  reactive-video-app:
    depends_on:
     - reactive-video-mongo
     - reactive-video-minio
    build:
      context: ../
      dockerfile: devops/app.Dockerfile
    image: reactive-video:1.0
    container_name: reactive-video-app
    ports:
      - '8081:8081'
    environment:
      - MONGODB_URI=mongodb://reactive-video-mongo:27017/files
      - S3_HOST=http://reactive-video-minio:9000
      - S3_ACCESS_KEY=ACCESS_KEY
      - S3_SECRET_KEY=SECRET_KEY
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge
    name: app_network
volumes:
  mongo-data: {}