spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  data:
    mongodb:
      uri: ${MONGODB_URI}
  main:
    web-application-type: reactive

s3:
  host: ${S3_HOST}
  access_key: ${S3_ACCESS_KEY}
  secret_key: ${S3_SECRET_KEY}

file:
  async-load-chunk-size: ${FILE_ASYNC_LOAD_CHUNK_SIZE}

server:
  port: ${SERVER_PORT}
