spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  data:
    mongodb:
      uri: mongodb://localhost:27017/files
  main:
    web-application-type: reactive

s3:
  host: "http://127.0.0.1:9000"
  access-key: "access-key"
  secret-key: "secret-key"

vk:
  oauth:
    endpoint: "https://mcs.mail.ru/auth/oauth/v1/token"
    provider: "mcs"
  vision:
    oauth:
      client-id: "vision-oauth-client-id"
      refresh-token: "vision-oauth-refresh-token"
    host: "https://smarty.mail.ru"
    endpoint:
      detect: "/api/v1/objects/detect"
  voice:
    oauth:
      client-id: "voice-oauth-client-id"
      refresh-token: "voice-oauth-refresh-token"
    endpoint: "https://voice.mcs.mail.ru/tts"

server:
  port: 8081
