spring:
  application:
    name: reactive-video
  data:
    mongodb:
      uri: mongodb://localhost:27017/files
  main:
    web-application-type: reactive

s3:
  host: "http://127.0.0.1:9000"
  access_key: "ObqQJsbLKk22VWYMyyQS"
  secret_key: "gO0ZOI52F0SncUn3EySmsSegxPeRBMckfrpHhy4A"

server:
  port: 8081

logging:
  level:
    root: DEBUG
