spring:
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  profiles:
    active: "@spring.profiles.active@"
  data:
    mongodb:
      uri: ${MONGODB_URI}
  main:
    web-application-type: reactive

s3:
  host: ${S3_HOST}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}

vk:
  oauth:
    endpoint: ${VK_OAUTH_ENDPOINT}
    provider: ${VK_OAUTH_PROVIDER}
  vision:
    oauth:
      client-id: ${VK_VISION_OAUTH_CLIENT_ID}
      refresh-token: ${VK_VISION_OAUTH_REFRESH_TOKEN}
    host: ${VK_VISION_HOST}
    endpoint:
      detect: ${VK_VISION_DETECT_ENDPOINT}
    detect-mode: ${VK_VISION_DETECT_MODE:multiobject}
  voice:
    oauth:
      client-id: ${VK_VOICE_OAUTH_CLIENT_ID}
      refresh-token: ${VK_VOICE_OAUTH_REFRESH_TOKEN}
    endpoint: ${VK_VOICE_ENDPOINT}

file:
  async-load-chunk-size: ${FILE_ASYNC_LOAD_CHUNK_SIZE}

server:
  port: ${SERVER_PORT}
