apiVersion: v1
kind: ConfigMap
metadata:
  name: reactive-video-backend-envs
data:
  VK_VISION_OAUTH_CLIENT_ID: VK_VISION_OAUTH_CLIENT_ID
  VK_VISION_OAUTH_REFRESH_TOKEN: VK_VISION_OAUTH_REFRESH_TOKEN
  VK_VOICE_OAUTH_CLIENT_ID: VK_VOICE_OAUTH_CLIENT_ID
  VK_VOICE_OAUTH_REFRESH_TOKEN: VK_VOICE_OAUTH_REFRESH_TOKEN
  FILE_ASYNC_LOAD_CHUNK_SIZE: "#{1024 * 1024}"